name: Backend CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Temurin JDK 17 (with Maven cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
          cache-dependency-path: backend/pom.xml

      - name: Make mvnw executable (just in case)
        run: chmod +x mvnw

      - name: Verify Docker (for Testcontainers)
        run: docker version

      - name: Build & test (unit + integration)
        run: ./mvnw -B -DskipTests=false test
